<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="sanil-Inspiron-5575" failures="1" tests="5" name="com.naveenautomation.tests.MyAccountInformationTest" time="69.779" errors="0" timestamp="2023-01-11T18:37:33 EST" skipped="0">
  <testcase classname="com.naveenautomation.tests.MyAccountInformationTest" name="VerifyUsersAreAbleToLoginSuccessFully" time="19.503"/>
  <system-out/>
  <testcase classname="com.naveenautomation.tests.MyAccountInformationTest" name="VerifyUsersAreAbleToLoginSuccessFully" time="9.149"/>
  <system-out/>
  <testcase classname="com.naveenautomation.tests.MyAccountInformationTest" name="VerifyUsersAreAbleToLoginSuccessFully" time="11.544"/>
  <system-out/>
  <testcase classname="com.naveenautomation.tests.MyAccountInformationTest" name="VerifyUsersAreAbleToLoginSuccessFully" time="15.764"/>
  <system-out/>
  <testcase classname="com.naveenautomation.tests.MyAccountInformationTest" name="VerifyUsersAreAbleToLoginSuccessFully" time="13.819">
    <failure message="FirstName doesnot match expected [Tony1] but found [Tony]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: FirstName doesnot match expected [Tony1] but found [Tony]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.naveenautomation.tests.MyAccountInformationTest.VerifyUsersAreAbleToLoginSuccessFully(MyAccountInformationTest.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- VerifyUsersAreAbleToLoginSuccessFully -->
  <system-out/>
</testsuite> <!-- com.naveenautomation.tests.MyAccountInformationTest -->
